### ISSUE TITLE
Mostrar un mensaje de error cuando el servidor no está corriendo

### ISSUE THREAD

**Issue by AguilaCudicio** [BarAgCud/tallerII#10]
Ahora mismo, si el servidor no está corriendo el programa no reacciona al presionar los botones de:
1. Terminar de hacer login
2. Terminar de hacer sign-up
Debería mostrar un mensaje de error en lugar de quedarse "trabado".

**Comment by GNico** [comment]
Agregados timeouts de conexion para reconocer el caso de error de que la ip establecida exista pero que no corresponda al servidor. 
Si el servidor no esta corriendo o la ip del servidor esta mal escrita, se arroja el mismo tipo de mensaje de error.

commit 98dc401b6b80b6ddb9a20d3d04f1212e15b1d719
