### ISSUE TITLE
Finalizar el display y envio de mensajes

### ISSUE THREAD

**Issue by GNico** [BarAgCud/tallerII#15]
Vincular la activity de chat con lo servicios de recepcion y envio de mensajes de la clase ServerRequest (utilizar inteface resultreceiver) para completar la funcionalidad.

**Comment by AguilaCudicio** [comment]
Corregido el bug de la caja (textedit) que se borraba cuando se recibían nuevos mensajes del servidor, en el commit https://github.com/BarAgCud/tallerII/commit/47aabccc9c58fc57011809096bed515722ac9248
Además, ahora la lista se actualiza con los nuevos mensajes del servidor en lugar de borrar los anteriores.

**Comment by GNico** [comment]
terminada la funcionalidad basica

Commit: f47d2f52585db75d77bba9b7fe7f75899f83517f
