### ISSUE TITLE
Implementar un buscador en la lista de contactos

### ISSUE THREAD

**Issue by GNico** [BarAgCud/tallerII#20]
debe permitirse al usuario filtrar la lista de contactos mostrada en pantalla de acuerdo a lo especificado en el buscador

**Comment by AguilaCudicio** [comment]
Edit Text y botón para empezar a implementar esta funcionalidad en el commit https://github.com/BarAgCud/tallerII/commit/16d36fcdfef500a501aab46e829aacbbf4c13996

**Comment by GNico** [comment]
Finalizado el buscador. Filtra la lista de contactos de acuerdo a lo que hay actualmente en la caja de texto.

e89cad38120fae544ac15355cc85933435b0bbb6
