### ISSUE TITLE
Editar la apariencia de la ventana de chat

### ISSUE THREAD

**Issue by AguilaCudicio** [BarAgCud/tallerII#22]
Agregar el avatar de las personas conectadas.

**Comment by AguilaCudicio** [comment]
Agregado campo para el avatar en https://github.com/BarAgCud/tallerII/commit/ab3e64a13dae591137ba8814adb1a1b084ae4df6

**Comment by GNico** [comment]
Ahora se muestran fotos de 33x33p en la lista de contactos y activity de chat, y fotos de mas resolucion en el perfil. 
f965a0d7d4f78c169ce9680a62538cda1df4e9af
