### ISSUE TITLE
Permitir al usuario mostrarse desconectado

### ISSUE THREAD

**Issue by AguilaCudicio** [BarAgCud/tallerII#26]
La opción debe mostrarse en la edición del perfil.

**Comment by AguilaCudicio** [comment]
Campo en la edición del perfil en https://github.com/BarAgCud/tallerII/commit/68349f43144f77a88f327ceeb89795a41012fd8c

**Comment by GNico** [comment]
Agregado comunicacion de la opcion al servidor f965a0d7d4f78c169ce9680a62538cda1df4e9af
