### ISSUE TITLE
Implementar la interfaz ResultReciever en las activities que lo requieran

### ISSUE THREAD

**Issue by GNico** [BarAgCud/tallerII#5]
La interfaz ResultReceiver debe ser implementada por las activities que requieren respuesta del servidor. Una vez que el servicio finaliza su tarea, este invoca al metodo "onReceiveResult(int resultCode, Bundle bundleData)" de la activity/interfaz. Se envia por parametro la respuesta del servidor (dentro del objeto Bundle) para que la activity la procese dentro de este metodo

**Comment by GNico** [comment]
quedo implementada la interfaz MyResultReceiver.receiver en la activity "ListViewFriendsActivity" 5b2cae9f37eeb572f9599fb156bc77d551b53a86

**Comment by AguilaCudicio** [comment]
Terminado de integrar en el commit https://github.com/BarAgCud/tallerII/commit/4014df2e9c9674039544f9d842c0376599eabf30
La interfaz grafica estaba funcionando con ejemplos hardcodeados en el login y registro, ahora toma los datos del servidor usando la nueva interfaz ResultReceiver.
