### ISSUE TITLE
Implementar la acción en el botón "Desconectar"

### ISSUE THREAD

**Issue by AguilaCudicio** [BarAgCud/tallerII#8]
En la ventana con la lista de amigos, hay un botón para desconectar el usuario, pero por ahora no hace nada. Debe implementarse esa acción.

**Comment by GNico** [comment]
El boton ahora llama al metodo de clase "logout" de la LoginActivity. Fue implementado asi para facil acceso desde otros componentes que requieran hacer logout cuando expira el token. 

commit 98dc401b6b80b6ddb9a20d3d04f1212e15b1d719
